h : 224
w : 224

# h : 224
# w : 224
# patch_size : 16
# n_targets : 4 # number of target patches to use
# decorrelation_weight : 0.1
n_epochs : 3
mini_epoch_len : 100000 # number of *steps* per mini-epoch
batch_size : 64
accumulation_steps : 8

data_path : "D:/Projects/image_datasets"
model : saccade
model_save_name : saccade
use_util_norm : False
warmup_epoch_fraction : 8 # fraction of epochs to use for warmup, 1/8 by default

val_every : 0 # run validation tasks every n mini-epochs, 0 means no validation
tests : ["corr_dim", "plot", "knn"] # the tests to run for validation

affine_cos_loss_weight : 1.0
affin_mag_loss_weight : 0.5
cycle_loss_weight : 0.5

lr : 0.001
min_lr : 0.0002
weight_decay : 0.0001
beta1 : 0.995
beta2 : 0.999