h : 224
w : 224
patch_size : 16
n_targets : 4 # number of target patches to use
n_epochs : 10
warmup_epoch_fraction : 8 # fraction of epochs to use for warmup, 1/8 by default
val_every : 0 # run a linear probing validation task every n epochs, 0 means no validation
batch_size : 64
data_path : "C:/Projects/image_datasets/"

lr : 0.001
weight_decay : 0.0001