h : 224
w : 224
patch_size : 16
n_targets : 4 # number of target patches to use
n_epochs : 1
mini_epoch_len : 100000 # number of *steps* per mini-epoch
batch_size : 64
accumulation_steps : 8
data_path : "D:/Projects/image_datasets"
warmup_epoch_fraction : 8 # fraction of epochs to use for warmup, 1/8 by default

val_every : 0 # run a linear probing validation task every n epochs, 0 means no validation
tests : ["corr_dim", "plot"]




lr : 0.001
weight_decay : 0.0001
beta1 : 0.995
beta2 : 0.999